from datetime import datetime
from pathlib import Path
from typing import Dict

import anthropic


class ReportBuilder:
    def __init__(self, api_key: str, model: str = "claude-opus-4-8"):
        self.client = anthropic.Anthropic(api_key=api_key)
        self.model = model

    def _compile_context(self, research_data: Dict) -> str:
        parts = []
        for topic, sources in research_data.items():
            parts.append(f"\n\n### TOPIC: {topic}")
            for i, src in enumerate(sources, 1):
                parts.append(f"\n--- Source {i}: {src['title']} ---")
                parts.append(f"URL: {src['url']}")
                parts.append(f"Content: {src['content'][:2500]}")
        return "".join(parts)

    def build_report(self, niche: str, research_data: Dict) -> str:
        context = self._compile_context(research_data)
        today = datetime.now().strftime("%B %d, %Y")
        total_sources = sum(len(v) for v in research_data.values())

        prompt = f"""You are a senior market research analyst producing a board-ready report.
Use ONLY the research data provided below. Cite sources inline as [Source: domain.com].
Do NOT invent statistics — if data is missing, flag it explicitly.

TODAY: {today}
NICHE: {niche}
SOURCES: {total_sources} across {len(research_data)} topics

RESEARCH DATA:
{context}

---

Write the full report in Markdown. Use this exact structure:

# {niche} Market Research Report
**Date:** {today} | **Sources:** {total_sources} | **Topics:** {len(research_data)}

---

## Executive Summary
> 3-5 concise bullet points — the most important takeaways for a decision-maker.

---

## 1. Market Overview
Current state of the market: definition, scope, maturity stage, geography.

## 2. Market Size & Growth
Specific figures, CAGR, historical trend and forecast (with source citations).

## 3. Key Industry Trends (2024–2025)
Numbered list of 5-7 major trends with supporting evidence per trend.

## 4. Competitive Landscape
Major players, market concentration, barriers to entry, competitive dynamics.

## 5. Target Customer Profile
Demographics, psychographics, buying behaviour, decision triggers, pain points.

## 6. Market Opportunities & Gaps
Underserved segments, whitespace, emerging niches — ranked by potential.

## 7. Challenges & Risks
Regulatory, competitive, economic, and operational risks.

## 8. Technology & Innovation
Emerging technologies, digital tools, automation trends shaping the space.

## 9. Financial Benchmarks
Typical pricing models, margins, revenue benchmarks for the industry.

## 10. Strategic Recommendations
5 specific, actionable recommendations for entering or growing in this market.

## 11. Data Sources & References
Bulleted list of all cited sources with full URLs.

---

*Report generated by AI Automation Solutions. Data reflects publicly available information as of {today}.*"""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=8000,
            messages=[{"role": "user", "content": prompt}],
        )
        return response.content[0].text

    def save_report(self, niche: str, report_content: str) -> str:
        Path("data/reports").mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_niche = "".join(c if c.isalnum() else "_" for c in niche)
        filename = f"data/reports/{safe_niche}_{timestamp}.md"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(report_content)
        return filename
